function [fitresult, gof] = createNdSmFit(filteredNd, filteredSm)
%CREATEFIT(FILTEREDND,FILTEREDSM)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: filteredNd
%      Y Output: filteredSm
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Aug-2022 15:40:21


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( filteredNd, filteredSm );

% Set up fittype and options.
ft = fittype( 'poly1' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Robust = 'Bisquare';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData, 'predobs' );
legend( h, 'filteredSm vs. filteredNd', 'untitled fit 1', 'Lower bounds (untitled fit 1)', 'Upper bounds (untitled fit 1)', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'filteredNd', 'Interpreter', 'none' );
ylabel( 'filteredSm', 'Interpreter', 'none' );
grid on


