function createAndesitefig(X1, Y1, Size1, andesites1)
%CREATEFIGURE(X1, Y1, Size1, andesites1)
%  X1:  vector of scatter x data
%  Y1:  vector of scatter y data
%  SIZE1:  vector of scatter size data
%  ANDESITES1:  vector of scatter color data

%  Auto-generated by MATLAB on 18-Aug-2022 15:29:41

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create scatter
scatter(X1,Y1,Size1,andesites1,'MarkerFaceColor','flat');

% Create ylabel
ylabel('Sm (ppm)');

% Create xlabel
xlabel('Nd (ppm)');

% Create title
title('Andesite Data');

box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',16);
% Create colorbar
colorbar(axes1);

xlim([0 200])
