function ECdownload = importAndesitefile1(workbookFile, sheetName, dataLines)
%IMPORTFILE1 Import data from a spreadsheet
%  EARTHCHEMDOWNLOAD15510 = IMPORTFILE1(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  EARTHCHEMDOWNLOAD15510 = IMPORTFILE1(FILE, SHEET) reads from the
%  specified worksheet.
%
%  EARTHCHEMDOWNLOAD15510 = IMPORTFILE1(FILE, SHEET, DATALINES) reads
%  from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  earthchemdownload15510 = importfile1("C:\Users\lsammon\OneDrive - MathWorks\Documents\MATLAB\A_Demos\UMD Geosciences Demo\earthchem_download_15510.xlsx", "Data", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Aug-2022 15:10:16

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 74);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "LATITUDE", "LONGITUDE", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "TYPE", "Var18", "Var19", "Var20", "SIO2", "TIO2", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42", "Var43", "Var44", "Var45", "Var46", "Var47", "Var48", "Var49", "Var50", "Var51", "Var52", "Var53", "Var54", "Var55", "Var56", "Var57", "Var58", "Var59", "Var60", "Var61", "Var62", "Var63", "ND", "SM", "EU", "Var67", "Var68", "Var69", "Var70", "Var71", "Var72", "Var73", "LU"];
opts.SelectedVariableNames = ["LATITUDE", "LONGITUDE", "TYPE", "SIO2", "TIO2", "ND", "SM", "EU", "LU"];
opts.VariableTypes = ["char", "char", "char", "char", "char", "char", "char", "char", "double", "double", "char", "char", "char", "char", "char", "char", "categorical", "char", "char", "char", "double", "double", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "double", "double", "double", "char", "char", "char", "char", "char", "char", "char", "double"];

% Specify file level properties
opts.MissingRule = "omitrow";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var18", "Var19", "Var20", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42", "Var43", "Var44", "Var45", "Var46", "Var47", "Var48", "Var49", "Var50", "Var51", "Var52", "Var53", "Var54", "Var55", "Var56", "Var57", "Var58", "Var59", "Var60", "Var61", "Var62", "Var63", "Var67", "Var68", "Var69", "Var70", "Var71", "Var72", "Var73"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "TYPE", "Var18", "Var19", "Var20", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42", "Var43", "Var44", "Var45", "Var46", "Var47", "Var48", "Var49", "Var50", "Var51", "Var52", "Var53", "Var54", "Var55", "Var56", "Var57", "Var58", "Var59", "Var60", "Var61", "Var62", "Var63", "Var67", "Var68", "Var69", "Var70", "Var71", "Var72", "Var73"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["LATITUDE", "LONGITUDE", "SIO2", "TIO2", "ND", "SM", "EU", "LU"], "TreatAsMissing", '');

% Import the data
ECdownload = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    ECdownload = [ECdownload; tb]; %#ok<AGROW>
end

ECdownload(1,:) = [];
end